import type {Metadata} from "next";
import {Inter, Sansation} from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sansation = Sansation({
  variable: "--font-sansation",
    weight: '700'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sansation.variable} antialiased font-body`}
      >
        {children}
      </body>
    </html>
  );
}
